version: '2'
services:
  mongodb:
    image: graanjonlo/mongodb:3.2.8
    ports:
     - "27017:27017"
     - "28017:28017"
    expose:
     - "27017"
     - "28017"
    volumes:
     - "/home/andy/docker/data/mongodb:/data/db"